### ISSUE TITLE
做一下正则匹配

### ISSUE THREAD

**Issue by freakkid** [freakkid/CheckInManager#7]
把**dev分支**CheckInManager/services/validator.js里面的空填一下，做下正则匹配的，**注意要用es6**，注意**readme.md**的要求，最后把代码pull到dev分支上，麻烦啦

**Comment by LebronX** [comment]
require那部分的写法换成import
把代码放进楠绚那边的代码里面
运行一下npm run lint
没有报错说明的你代码是es6格式了
